### ISSUE TITLE
Add support for multithreaded code

### ISSUE THREAD

**Issue by NielkS** [elastic/apm-agent-python#499] opened 2019-06-20 06:54 UTC
Is it possible to add support for instrumentation of code running in several threads ?

From both my experience (django app using a ThreadPoolExecutor) and [this thread](https://discuss.elastic.co/t/instrumenting-python-futures-calls/148194) from one year ago on elastic forum, I think this is not supported yet.

**Comment by beniwohli** [comment] 2019-08-29 13:29
@NielkS sorry for the late reply, this needed some time for investigation. I recently played around a bit with `ThreadPoolExecutor`, and came up with a semi-acceptable solution.

The underlying issue is that we rely on thread-local variables to access the current transaction when creating spans. If you create worker threads, they can't access that thread-local. So the manual workaround is to get the current transaction in the main thread, pass it into the callable, and update the thread-local from inside the worker thread.

Here's an example how that could look, based on the `ThreadPoolExecutor` example from the Python docs:

    import concurrent.futures
    import urllib.request
    
    from elasticapm.traces import execution_context
    
    
    URLS = ['http://www.foxnews.com/',
            'http://www.cnn.com/',
            'http://europe.wsj.com/',
            'http://www.bbc.co.uk/',
            'http://some-made-up-domain.com/']
    
    # Retrieve a single page and report the URL and contents
    def load_url(url, timeout, transaction):
        execution_context.set_transaction(transaction)
        with urllib.request.urlopen(url, timeout=timeout) as conn:
            return conn.read()
    
    def process_urls():
        # We can use a with statement to ensure threads are cleaned up promptly
        with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
            # get current transaction from thread-local store
            transaction = execution_context.get_transaction()
            # Start the load operations and mark each future with its URL
            future_to_url = {executor.submit(load_url, url, 60, transaction): url for url in URLS}
            for future in concurrent.futures.as_completed(future_to_url):
                url = future_to_url[future]
                try:
                    data = future.result()
                except Exception as exc:
                    print('%r generated an exception: %s' % (url, exc))
                else:
                    print('%r page is %d bytes' % (url, len(data)))
        return "OK"

(Note that `execution_context` is not documented API, and as such can change without warning in a future release.)

One option for a more automatic support could be the provide a subclass of `ThreadPoolExecutor` that handles getting/setting the current transaction automatically. Does that sound useful?

**Comment by NielkS** [comment] 2019-10-15 06:43
Hi @beniwohli,
Sorry for the delay as well - thanks for the workaround, it's working fine (without too much code change on my project).
Should I keep this ticket open to have a long-term solution (without any code change user-side ), or is it technically impractical to implement that ?

**Comment by basepi** [comment] 2020-10-07 18:12
It's possible that with modern versions of python (3.7+) that support `contextvars`, this now just works. Or, at least it will, once code and frameworks are updated to properly utilize and propagate `contextvars` across threads.

I'm going to close this since you had a workaround and `contextvars` are the future!

**Closed by basepi** 2020-10-07 18:12 UTC

**Comment by mkkeffeler** [comment] 2021-02-24 23:14
Seems like this may not work now. I got this error 

```
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] File "/home/vcap/deps/0/python/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] for element in iterable:
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] File "/home/vcap/deps/0/python/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] yield fs.pop().result()
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] File "/home/vcap/deps/0/python/lib/python3.8/concurrent/futures/_base.py", line 439, in result
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] return self.__get_result()
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] File "/home/vcap/deps/0/python/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] raise self._exception
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] File "/home/vcap/deps/0/python/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] obj = _ForkingPickler.dumps(obj)
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] File "/home/vcap/deps/0/python/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] cls(buf, protocol).dump(obj)
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] TypeError: cannot pickle '_thread.lock' object
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] During handling of the above exception, another exception occurred:
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] Traceback (most recent call last):
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] File "/home/vcap/deps/0/python/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] response = self.full_dispatch_request()
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] File "/home/vcap/deps/0/python/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] rv = self.handle_user_exception(e)
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] File "/home/vcap/deps/0/python/lib/python3.8/site-packages/flask_restx/api.py", line 638, in error_router
2021-02-24T17:13:05.261-06:00 [APP/PROC/WEB/0] [ERR] return original_handler(f)

```

**Comment by basepi** [comment] 2021-02-25 17:19
@mkkeffeler would you mind opening a new issue? It's not obvious to me what's going wrong in the logs you've provided, we'll probably need more details about how to reproduce this issue (and whether it goes away without the agent enabled).

**Comment by leandromachado-openco** [comment] 2023-10-25 14:58
I had the same issue and this blog post helped: https://kobybass.medium.com/python-contextvars-and-multithreading-faa33dbe953d

```
class ContextExecutor(ThreadPoolExecutor):
    def __init__(self):
        self.context = contextvars.copy_context()
        super().__init__(initializer=self._set_child_context)
    def _set_child_context(self):
        for var, value in self.context.items():
            var.set(value)
```
