### ISSUE TITLE
buffer flushing based on queue size

### ISSUE THREAD

**Issue by EgorRedkozubov** [elastic/apm-agent-python#1819] opened 2023-04-28 20:15 UTC
**Describe the bug**: ...

**To Reproduce**

1. load buffer to be more than max buffer size (queue_size should have less than buffer.size)

**Environment (please complete the following information)**
- OS: Linux
- Python version: 3.10
- Agent version: master

**Additional context**

here
https://github.com/elastic/apm-agent-python/blob/21fb04aa8cf6e2f41dcebf088a3c06594883d3e1/elasticapm/transport/base.py#L171
buffer flushes on queue_size > self._max_buffer_size
when it should be flashed base on buffer.size > self._max_buffer_size:

**Comment by basepi** [comment] 2023-04-28 20:56
Are you actually running into unexpected behavior here? I think this is just a case of confusing variable names, not an actual bug, see this line:

https://github.com/elastic/apm-agent-python/blob/21fb04aa8cf6e2f41dcebf088a3c06594883d3e1/elasticapm/transport/base.py#L156

The `queue_size` variable is actually the buffer size.

**Comment by EgorRedkozubov** [comment] 2023-04-28 20:58
Queue size in my case was 10, buffer size was 800000

**Comment by basepi** [comment] 2023-04-28 21:35
Strange! I guess I need to go see what that `buffer.fileobj.tell()` does, and see why it's not matching. Your fix may be the correct one, I just want to double check. For now I'll get the tests running and we'll see what that does, and then I'll look next week.

**Comment by basepi** [comment] 2023-05-01 22:24
OK, I don't think this is actually a bug. `buffer.fileobj.tell()` will give us the *compressed* size of the buffer. Pretty sure `buffer.size()` will give us the uncompressed size. Turns out, APM data compresses __really well__!

**Comment by basepi** [comment] 2023-05-05 19:26
I'm going to close this, please keep me posted if you think there's a real bug here, it's a critical code path!

**Closed by basepi** 2023-05-05 19:26 UTC
Labels: agent-python, community, triage
