### ISSUE TITLE
[META 637] Enable custom metrics collection with AWS Lambda

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-python#1537] opened 2022-04-25 06:03 UTC
See meta issue and spec for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/637
- Spec issue: https://github.com/elastic/apm/issues/638

**Comment by AlexanderWert** [comment] 2022-04-25 06:05
duplicate of https://github.com/elastic/apm-agent-python/issues/1534

**Closed by AlexanderWert** 2022-04-25 06:05 UTC
Labels: agent-python
