### ISSUE TITLE
Unhandled exception with FastAPI and client disabled blocks the response

### ISSUE THREAD

**Issue by ca-simone-chiorazzo** [elastic/apm-agent-python#993] opened 2020-12-29 08:20 UTC
**Describe the bug**: ...
Using FastAPI and the ElasticAPM middleware, we noticed that for an **api view** with APM **disabled** (via config) the HTTP call goes stuck in the method "capture_exception" that never returns.

**To Reproduce**

1. ... Install fast API and APM client
2. ...Install ElasticAPM middleware and configure client with *enabled=false*
3. ...Raise an unhandled exception from an api
4. ...You can see that the HTTP response is never returned to the client and the call remains in a limbo
5. remove elastic middleware
6. Fire again an unhandled exception
7. You can see that the exception is then managed and a 500 is returned to the client

**Environment (please complete the following information)**
- Python version: 3.8.6
- Framework and version: Fastapi 0.63.0
- APM Server version: 
- Agent version: 5.10.0

**Comment by beniwohli** [comment] 2021-01-04 15:17
Hi @ca-simone-chiorazzo 

I tried reproducing this first in a test (albeit just with Starlette, which is the layer we hook into), and then by adding an `assert False` [here](https://github.com/nsidnev/fastapi-realworld-example-app/blob/master/app/api/routes/tags.py#L14) in [fastapi-realworld-example-app](https://github.com/nsidnev/fastapi-realworld-example-app). I didn't notice anything blocking with `enabled=false`.

If you run your fastapi in the console and hit `Ctrl-C` when it blocks, do you get any traceback that would indicate where the code is blocking exactly?

**Comment by ca-simone-chiorazzo** [comment] 2021-01-04 15:46
Hi @beniwohli

thanks to having given a look to this issue.

I've tried what you suggest, but once I hit `Ctrl-C` uvicorn tries to wait for pending connections forever..

I report here the log:
```
INFO:     Uvicorn running on http://0.0.0.0:8666 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8666 (Press CTRL+C to quit)
INFO:     Started reloader process [26394] using statreload
INFO:uvicorn.error:Started reloader process [26394] using statreload
Could not register elasticapm.metrics.sets.cpu.CPUMetricSet metricset: psutil not found. Install it to get system and process metrics
WARNING:elasticapm.metrics:Could not register elasticapm.metrics.sets.cpu.CPUMetricSet metricset: psutil not found. Install it to get system and process metrics
WARNING:rollbar:Rollbar already initialized. Ignoring re-init.
INFO:     Started server process [26399]
INFO:uvicorn.error:Started server process [26399]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
^CINFO:     Shutting down
INFO:uvicorn.error:Shutting down
INFO:     Waiting for connections to close. (CTRL+C to force quit)
INFO:uvicorn.error:Waiting for connections to close. (CTRL+C to force quit)
^CINFO:     Finished server process [26399]
INFO:uvicorn.error:Finished server process [26399]
INFO:     Stopping reloader process [26394]
INFO:uvicorn.error:Stopping reloader process [26394]

```

**Comment by beniwohli** [comment] 2021-01-04 16:14
@ca-simone-chiorazzo I see you have Rollbar installed. Do you see the same behavior if Rollbar is disabled?

**Comment by ca-simone-chiorazzo** [comment] 2021-01-04 16:23
@beniwohli Nope. Rollbar is currently disabled but it does not hang the application for an unhandled exception. If I remove the ElasticAPM middleware all return to works fine (with still rollbar installed and disabled)

**Comment by basepi** [comment] 2021-01-07 17:17
@ca-simone-chiorazzo Can you try to create a smaller reproduction case for us? It seems to me that this must be some interaction with your environment or other dependencies, since @beniwohli [tried with the fastapi-realworld-example-app](https://github.com/elastic/apm-agent-python/issues/993#issuecomment-754035433) above.

For example, although rollbar is disabled, it may still be setting up some integrations which are causing this bug. (In the log above, it says rollbar is already initialized, which leads me to believe that it's still doing *something* even if it's not actually reporting the errors when they happen.) Perhaps removing rollbar completely will give a different result?

**Comment by basepi** [comment] 2021-01-07 17:46
I did spot a potential issue as well -- if you get a moment can you try setting `instrument=False` along with `enabled=False`? It appears we may be instrumenting for starlette even if the agent is disabled. I'm going to fix that shortly but it would also be nice to verify that's the problem.

**Comment by ca-simone-chiorazzo** [comment] 2021-01-07 17:56
@basepi It's the same result of my initial investigation on the issue, but I've not found the culprit point. I was also noticing that the enabled config was not considered in the "capture_exception" method of the middleware.

I've tried with the following settings

```
        {
            'SERVICE_NAME': "Service name",
            'SECRET_TOKEN': APM_TOKEN,
            'SERVER_URL': APM_ENDPOINT,
            'COLLECT_LOCAL_VARIABLES': 'errors',
            'CAPTURE_BODY': 'errors',
            'ENABLED': False,
            'INSTRUMENT': False,
            'RECORDING': False,
            'DEBUG': False,
            'SERVICE_VERSION': APP_VERSION,
            'ENVIRONMENT': 'local',
            'TRANSACTIONS_IGNORE_PATTERNS': ['GET /favicon.ico'],
        }
```

but the problem persists.

I can prepare a reproducible demo as soon as I've time

**Comment by basepi** [comment] 2021-01-07 19:18
Thanks, we would appreciate that, it would be very helpful.

**Comment by basepi** [comment] 2021-02-22 18:29
@ca-simone-chiorazzo any chance you have time to help get us a reproduction case here? We'd really like to get this fixed.

**Comment by chiora93** [comment] 2021-02-28 18:44
@basepi Sorry for the late, I've tried to reproduce it on my personal windows computer without any success using the following setup:

main.py
```python
from fastapi import FastAPI

app = FastAPI()

from elasticapm.contrib.starlette import make_apm_client, ElasticAPM

apm = make_apm_client({
    'SERVICE_NAME': "Service name",
    'SECRET_TOKEN': "token",
    'SERVER_URL': "https://endpoint.com",
    'COLLECT_LOCAL_VARIABLES': 'errors',
    'CAPTURE_BODY': 'errors',
    'ENABLED': False,
    'INSTRUMENT': False,
    'RECORDING': False,
    'DEBUG': False,
    'SERVICE_VERSION': 1.0,
    'ENVIRONMENT': 'local',
    'TRANSACTIONS_IGNORE_PATTERNS': ['GET /favicon.ico'],
})
app.add_middleware(ElasticAPM, client=apm)


@app.get("/")
async def root():
    raise Exception("Hello exception")


@app.get("/2")
def root2():
    raise Exception("Hello exception")

```
requirements.txt
```bash
fastapi==0.63.0
fastapi[all]
elastic-apm==5.10.0
rollbar
```

I'll try to reproduce it on the MacBook (where I encountered the issue the first time) as soon as I have time

**Comment by basepi** [comment] 2021-03-01 16:01
No problem. Since you've been unable to reproduce so far, I'm going to close this for now. Please comment if you manage to reproduce it and we'll get it re-opened!

**Closed by basepi** 2021-03-01 16:01 UTC
Labels: agent-python
