### ISSUE TITLE
Unable to run on uwsgi

### ISSUE THREAD

**Issue by cdvv7788** [elastic/apm-agent-python#441] opened 2019-03-27 23:27 UTC
**Describe the bug**: Middleware not sending data to the server

**To Reproduce**
1. Setup a django project (2.0) with python 3.5
2. Configure elastic-apm:
Service name is set, good job!
  * optional SECRET_TOKEN not set

SERVER_URL http://blablabla.com looks fine

DEBUG mode is disabled! Looking good!

Tracing middleware is configured! Awesome!

Looks like everything should be ready!

**Expected behavior**: Metrics and transactions should be recorded in kibana dashboard. The test (python manage.py test) error is recorded successfully.

**Environment (please complete the following information)**
- OS: Ubuntu 16.04
- Python version: 3.5
- Framework and version [e.g. Django 2.1]: 2.0
- APM Server version: 6.7.0
- Agent version: 4.2.1

**Additional context**

- Agent config options 
  <details>
Nothing out of the ordinary. In my settings, a dictionary with SERVER_URL (http) and SERVICE_NAME
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
amqp==2.4.2
argon2-cffi==19.1.0
Babel==2.6.0
billiard==3.5.0.5
boto3==1.9.114
botocore==1.12.114
celery==4.2.2
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
Collectfast==0.6.2
coreapi==2.3.3
coreschema==0.0.4
defusedxml==0.5.0
Django==2.0.13
django-allauth==0.38.0
django-anymail==5.0
django-crispy-forms==1.7.2
django-environ==0.4.5
django-model-utils==3.1.2
django-redis==4.10.0
django-storages==1.7.1
djangorestframework==3.9.1
docutils==0.14
elastic-apm==4.2.1
flower==0.9.2
gunicorn==19.9.0
idna==2.8
itypes==1.1.0
Jinja2==2.10
jmespath==0.9.4
kombu==4.3.0
MarkupSafe==1.1.1
oauthlib==3.0.1
Pillow==5.4.1
pkg-resources==0.0.0
psutil==5.6.1
psycopg2==2.7.4
pycparser==2.19
python-dateutil==2.8.0
python-slugify==2.0.1
python3-openid==3.1.0
pytz==2018.9
pyzmq==16.0.4
redis==2.10.6
requests==2.21.0
requests-oauthlib==1.2.0
s3transfer==0.2.0
six==1.12.0
tornado==4.5.3
Unidecode==1.0.23
uritemplate==3.0.0
urllib3==1.24.1
vine==1.3.0
    ```
  </details>

Edit:
I was able to send data to the apm-server using django's dev server, so the issue is not there. I am trying to check if there is an issue with uwsgi. I enabled threads, as mentioned in the docs, but still no luck:
Thu Mar 28 02:16:41 2019 - Python main interpreter initialized at 0x1f7f750
Thu Mar 28 02:16:41 2019 - python threads support enabled
Thu Mar 28 02:16:41 2019 - your server socket listen backlog is limited to 100 connections
Thu Mar 28 02:16:41 2019 - your mercy for graceful operations on workers is 60 seconds
Thu Mar 28 02:16:41 2019 - mapped 166144 bytes (162 KB) for 2 cores
Thu Mar 28 02:16:41 2019 - *** Operational MODE: threaded ***

**Comment by cdvv7788** [comment] 2019-03-28 02:29
I was able to fix it by adding:
    lazy-apps = true
In my uwsgi.ini file.
I found this at https://github.com/jnhasty/uwsgi-newrelic/blob/master/app.ini. It seems that newrelic's agent requires a similar setup to work with uwsgi.
Feel free to close. I won't do it so maintainers can decide if this is worth documenting (took me a while to make this work).

**Comment by beniwohli** [comment] 2019-04-01 12:31
Hi @cdvv7788 

We added some handling for uwsgi specifically in 4.2.1, but it looks like that's not working for you :(

The problem is with uwsgi's prefork model, uwsgi will load the app before forking the worker processes. Because we initialize a background thread during the app startup, the forked processes don't have our threads.

uwsgi has a `postfork` utility function with which we can register a function that will run after the fork. We use that to postpone thread startup until after the fork. I'll try to investigate why this doesn't seem to work for you.

`lazy-apps = true` instructs uwsgi to only load the app after the fork, which is a good workaround for this issue. It will however incur some additional memory use

**Comment by nfj25** [comment] 2019-04-01 17:10
I also had the same problem. Only worked with lazy-apps = true with a very basic app (django-admin with jet).
Discovered the workaround after some trial and error. Should have looked here before :)

elastic-apm==4.2.1
Django==2.1.5

# rpm -qa | grep uwsgi
uwsgi-plugin-python36-2.0.17.1-1.el7.x86_64
uwsgi-2.0.17.1-1.el7.x86_64
uwsgi-plugin-common-2.0.17.1-1.el7.x86_64

CentOS Linux release 7.6.1810

**Comment by Giaco9** [comment] 2019-05-26 06:44
Hi, at my company we are in the middle of the process of enabling the elastic apm in our main web services and I think we may have the same problem. We run a Django application (version 1.11)  on Amazon ECS with uwsgi configured in this way (bakery is the name of the application):

[uwsgi]
plugin=python
chdir=/bakery/
module=clouda.wsgi:application
master=true
pidfile=/bakery/bakery.pid
vacuum=True
max-requests=5000
processes=6
enable-threads=true
static-map=/static_res=/bakery/static
buffer-size = 16384
http=0.0.0.0:8001
log-format=[pid: %(pid)|app: -|req: -/-] %(addr) (%(user)) {%(vars) vars in %(pktsize) bytes} [%(ctime)] %(method) %(uri) => generated %(rsize) bytes in %(msecs) msecs (%(proto) %(status)) %(headers) headers in %(hsize) bytes (%(switches) switches on core %(core)) agent %(uagent)

The apm agent is 4.1.0 and the apm server version is the 7.1.0.

Starting the app everything works as expected, I can see all the transactions been recorded correctly. After a while I see a drop in the incoming requests. Do you think enabling lazy-apps = true will solve the issue? The app is pretty big so the memory load can be an issue but if I'm sure that this would solve the issue I can live with that and change ECS settings properly. 
In the case lazy-app doesn't solve the issue can you please help me with mine?

Thanks

**Comment by jaap3** [comment] 2019-09-16 12:46
I'm seeing this exact behaviour as well after I upgraded from elastic-apm 3.0.4 to elastic-apm 5.1.2.

The applications use Django 2.2.2. The application server is uWSGI (`uwsgi-2.0.17.1-2.el7.x86_64`) using the uWSGI python 3.6 plugin (`uwsgi-plugin-python36u-2.0.17.1-1.ius.el7.x86_64`) (`enable-threads` is set to `true`).

The APM Server version we're using is 6.8.2 (soon te be upgraded to 6.8.3).

`./manage.py elasticapm check` says everyting is ok (middleware is installed, DEBUG false etc.)
`./manage.py elasticapm test` correctly sends a test exception, which shows up in Kibana

However request/response metrics do not show up in Kibana.

Downgrading the elastic-apm client to version 3.0.4 works (I also tried downgrading to 4.x but this didn't help). The upgrade to elastic-apm 5.1.2 only works after adding the `lazy-apps = true` workaround to the applications uwsgi settings.

In addition, without the `lazy-apps` workaround reloading the uWSGI application logs the following exception in Sentry:

```
Exception(most recent call first)

ValueError: close timed out
  File "elasticapm/utils/compat.py", line 65, in uwsgi_atexit
    func()
  File "elasticapm/base.py", line 266, in close
    self._transport.close()
  File "elasticapm/transport/base.py", line 293, in close
    super(AsyncTransport, self).close()
  File "elasticapm/transport/base.py", line 241, in close
    raise ValueError("close timed out")
```

**Comment by dougbyrne** [comment] 2019-12-20 01:05
I had to manually install the `uwsgidecorators` module. The uwsgi docs didn't make it clear if it's supposed to be automatically injected like the `uwsgi` module, but it wasn't. 

I don't know how common this is, we could probably stand to upgrade our uwsgi. Maybe APM can log a warning if it's able to import `uwsgi` but not `uwsgidecorators` here: https://github.com/elastic/apm-agent-python/blob/master/elasticapm/utils/compat.py#L179

**Comment by beniwohli** [comment] 2020-02-18 10:49
We just released a new version of the agent that should fix this issue, can you try to install 5.4.1 and see if the problem goes away?

I'll close this issue for now, please re-open it if you still encounter the bug.

**Closed by beniwohli** 2020-02-18 10:49 UTC
Labels: [zube]: In Review

**Comment by jstockwin** [comment] 2020-02-18 11:37
I am having the same problem as above (not fixed by installing `uwsgidecorators` or by `lazy-apps=true`), which I put down to this issue.

I've just redeployed using `elastic-apm==5.4.1` (I'm `django==1.11.28` and still have `lazy-apps=true`, `enable-threads = true`, and `single-interpreter = true`), but still have the same issue.

I can see only the first few requests to my health-check endpoint in APM, and then nothing. The test error from `manage.py` gets through fine, as in the original report. I'll wait for someone else to confirm before re-opening in case it's me doing something else wrong.

**Comment by flimebelt** [comment] 2021-01-18 20:02
Just a quick test, follow my...

================
api.py
================
# APM Server
app.config['ELASTIC_APM'] = {
    'SERVICE_NAME': __service_name,
    # 'SECRET_TOKEN': '',
    'SERVER_URL': os.environ.get('ELASTIC_APM_URL', 'http://localhost:8200')
}
apm = ElasticAPM(app)

================
wsgi.py
================
import os

from elasticapm.handlers.logging import LoggingHandler
from api import app, apm

if __name__ == '__main__':
    # Create a logging handler and attach it.
    handler = LoggingHandler(client=apm.client)
    # handler.setLevel(logging.WARN)
    app.logger.addHandler(handler)
    app.run(
        host = os.environ.get("GATEWAYAPI_HOST", "localhost"),
        port = os.environ.get("GATEWAYAPI_PORT", "5000"),
        debug = False,
        threaded = True
    )

================
wsgi.ini
================
[uwsgi]
project = gateway_api
module = wsgi: app
master = true
processes = 5
http = 0.0.0.0 anymore
die-on-term = true
enable-threads = true
lazy-apps = true


It works for me! I hope to help someone! =]
