### ISSUE TITLE
APM agent not using full server_url

### ISSUE THREAD

**Issue by RandalMoss** [elastic/apm-agent-python#373] opened 2018-12-28 21:57 UTC
**Describe the bug**:
I'm having a similar issue that was described in the apm-agent-java issues: https://github.com/elastic/apm-agent-java/issues/339

I am using a url that looks like: https://test.url/with/path
The logs from the APM agent show the following:
` Failed to submit message: 'Connection to APM Server timed out (url: https://test.url/intake/v2/events, timeout: 5 seconds)'`

The path that I have at the end gets removed.

**To Reproduce**

1. Configure SERVER_URL=https://test.url/<path>
2. Trigger an APM event

**Expected behavior**:

I expected that the SERVER_URL variable would take the full URL and not just the domain part.

**Environment (please complete the following information)**
- OS: Using Docker for Mac version 2.0.0.0-mac81 with base image python:3.7
- Python version: python 3.7
- Framework and version [e.g. Django 2.1]: Flask 1.0.2
- APM Server version: docker.elastic.co/apm/apm-server:6.5.4
- Agent version: 4.0.3

**Comment by beniwohli** [comment] 2019-01-02 13:21
@RandalMoss thanks for opening the issue. This is caused by a (in my opinion) somewhat surprising behavior of `urljoin(url, path)` if the `path` argument starts with a `/`. It basically strips the whole path from `url`.

I have a fix ready in #376, and will merge/release it in the coming days

**Comment by beniwohli** [comment] 2019-01-31 15:16
This has been released in the 4.1.0 version of the agent

**Closed by beniwohli** 2019-01-31 15:16 UTC
Labels: [zube]: In Review
