### ISSUE TITLE
[META 744] Implement Azure Functions Tracing

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-python#1721] opened 2023-01-13 07:21 UTC
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/744

**Comment by z1c0** [comment] 2023-01-13 07:22
Duplicate of https://github.com/elastic/apm-agent-python/issues/1675

**Closed by z1c0** 2023-01-13 07:22 UTC
Labels: agent-python
