### ISSUE TITLE
dbapi2 extract_signature omits T-SQL table name if in square brackets

### ISSUE THREAD

**Issue by sparrowt** [elastic/apm-agent-python#1071] opened 2021-03-15 18:15 UTC
**Describe the bug**: the shortened SQL signature used as the span name (for dbapi2 database queries) does not show the table name but only a single square bracket `[` if the SQL query uses T-SQL `[table_name]` syntax.

**To Reproduce**

1. With the environment as listed below, use Django to make any old SELECT query to an MS SQL database - it will look like e.g:
```SELECT [table_name].[id], [table_name].[foo], [table_name].[bar] FROM [table_name] WHERE [table_name].[id] = ?```
2. This python APM agent will report the query to Elastic with name: `SELECT FROM [` not `SELECT FROM [table_name]`
3. The knock-on is that in Elastic when viewing a transaction trace, you can't see the table name:
![image](https://user-images.githubusercontent.com/793763/111199958-215b2f00-85b9-11eb-97bd-38e4dca45e98.png)
and in order to see which table is accessed, you have to click through to "Span details" every time to view the full SQL.

**Environment**
- OS: Windows
- Python version: 3.8.8
- Framework and version: Django 2.2.19
- APM Server version: 7.6.2 (I think - Kibana is v7.6.2)
- Agent version: 5.8.1
- Other relevant packages: `pyodbc==4.0.28`, `django-mssql-backend==2.4.2`

**Cause**
The key method seems to be [`extract_signature`](https://github.com/elastic/apm-agent-python/blob/09ce4f6dfc966dfdd3f6e5fbc142e688da84aeb5/elasticapm/instrumentation/packages/dbapi2.py#L152) which is used by both `PyMSSQLCursorProxy` and `PyODBCCursorProxy`.  For a `SELECT` statement it calls `look_for_table(sql, "FROM")` and that method calls:
- [`tokenize`](https://github.com/elastic/apm-agent-python/blob/09ce4f6dfc966dfdd3f6e5fbc142e688da84aeb5/elasticapm/instrumentation/packages/dbapi2.py#L92) which returns a list such as `[... 'FROM', ' ', '[', 'table_name', ']', ' ', ...]`
- `_scan_for_table_with_tokens`=>[`scan`](https://github.com/elastic/apm-agent-python/blob/09ce4f6dfc966dfdd3f6e5fbc142e688da84aeb5/elasticapm/instrumentation/packages/dbapi2.py#L97) which returns the next lexeme after `FROM` as being just `[` rather than `[table_name]`.

**How to fix**
Does `scan` need to be taught another special-case to handle literals enclosed in `[...]` as it does for `'`, `"` and `` ` ``?  This would be a non-trivial change given the existing code assumes the starting & ending tokens are the same.

**Comment by felixbarny** [comment] 2021-03-16 09:12
Should be fixed with #919, which will extract `SELECT FROM table_name`.

**Comment by sparrowt** [comment] 2021-03-16 11:01
Thanks @felixbarny, I came across that ticket but forgot to mention it above - figured this might be covered by that general plan though thought it might be worth a separate issue for searchability.  Also wondered if perhaps depending on the timescales of #919 there might be a way to fix this case sooner.  But I appreciate that by the time I got to the end of writing the ticket, there didn't seem an obvious quick fix (otherwise this would be a PR!) so if you'd prefer to close this as a dupe that's fine! Thanks again.

**Comment by basepi** [comment] 2021-06-10 15:54
Sorry for the slow reply here but I think we are going to close this as a dupe of #919. As you pointed out, there's not obvious quick fix here and if we're going to spend time, it will be to bring things in line with the cross-agent spec defined in #919.

**Closed by basepi** 2021-06-10 15:54 UTC
Labels: agent-python
