### ISSUE TITLE
Application is crashing as APM agent is not able to send events to APM server

### ISSUE THREAD

**Issue by isha1404** [elastic/apm-agent-python#1460] opened 2022-02-09 14:41 UTC
I am looking for an option where if the APM agent fails to send events to APM server it should not crash my application . It will shut down silently.

**Environment (please complete the following information)**
- OS: [e.g. Linux]
- Python version:
- Framework and version [e.g. Django 2.1]: Django
- APM Server version:
- Agent version:

**Comment by isha1404** [comment] 2022-02-10 05:34
Its not failing while startup,  our celery tasks/API's were getting failed as the agent was throwing this error : https://www.elastic.co/guide/en/apm/guide/master/common-problems.html#queue-full while flushing because Elasticsearch cluster was underpowered which makes totally sense. Since we are using APM to monitor the performance of application , we don't want our application to throw out errors even though there is some issue with APM. Is there any such configuration where we can say if something is wrong with APM agent it will silently shut down, not giving error in the application itself.

**Comment by isha1404** [comment] 2022-04-19 14:10
Hi our whole elastic cluster was down resulting this issue.

**Comment by basepi** [comment] 2022-04-19 15:59
Right, but my question is not about the elastic cluster, it's about your celery tasks.

Did the celery tasks actually abort as a result of this issue, or did you just see error logs?

**Comment by basepi** [comment] 2022-05-03 16:10
Alright, I spun up a basic Django app with some celery tasks.

I have a tiny task called `add`, which adds two numbers.

Here is my django view:

```
def index(request):
    add.delay(2, 2)
    add.apply_async((2, 2), countdown=10)
    return HttpResponse("Hello, world.")
```

I am using a mock APM Server which returns a 504 error after a 5 second delay. The idea is to get the 504 between the two tasks, to see if the second task runs.

Here are the logs from my celery worker:

```
[2022-05-03 15:56:45,798: INFO/ForkPoolWorker-8] Task polls.tasks.add[255e1683-8323-4dfd-a357-d87b81ca00cd] succeeded in 0.0024197502061724663s: 4
[2022-05-03 15:56:51,051: ERROR/ForkPoolWorker-8] Failed to submit message: 'HTTP 504: boom'
Traceback (most recent call last):
  File "/Users/basepi/.pyenv/versions/3.10.2/envs/django_test/lib/python3.10/site-packages/elasticapm/transport/base.py", line 275, in _flush
    self.send(data, forced_flush=forced_flush)
  File "/Users/basepi/.pyenv/versions/3.10.2/envs/django_test/lib/python3.10/site-packages/elasticapm/transport/http.py", line 108, in send
    raise TransportException(message, data, print_trace=print_trace)
elasticapm.transport.exceptions.TransportException: HTTP 504: boom
[2022-05-03 15:56:55,990: INFO/ForkPoolWorker-8] Task polls.tasks.add[7fc419c4-47e4-44b4-97f7-1f533f14d1bd] succeeded in 0.0010877919849008322s: 4
```

As you can see, the first task succeeds, then I get the APM Server error, and then the second task succeeds.

I haven't been able to make my celery worker stop working due to APM Server errors.

I will note that these error logs can definitely be improved, and that's something that we'll add to our list of improvements.

(I should also note, it's not important that I'm using a 504 vs a 503, we [handle them exactly the same](https://github.com/elastic/apm-agent-python/blob/f476ea0ff73b69affbc4f51325eaedd09d48479f/elasticapm/transport/http.py#L100-L108) -- I just already had a mock APM Server set up to throw 504 errors.)

I'm using Django 4.0.4 and Celery 5.2.6.

I think we'll need to come up with a basic example that can be used to reproduce this issue before we can continue investigating.

**Comment by basepi** [comment] 2022-05-23 14:39
@isha1404 since your support case is currently closed, I'm going to close this issue as well. We'll follow up if your support issue is re-opened or if you hit this again.

**Closed by basepi** 2022-05-23 14:39 UTC
Labels: bug, agent-python, community
