### ISSUE TITLE
APM adding query params causing 400 bad request error during ES query

### ISSUE THREAD

**Issue by Thematrixme** [elastic/apm-agent-python#662] opened 2019-12-10 09:05 UTC
**Bug description**

I have an API that queries ElasticSearch and that I'm trying to monitor thanks to APM. Somehow I have the exact same problem described in this (quite old) discussion:
https://discuss.elastic.co/t/apm-adding-query-params-causing-400-bad-request-error-during-es-query/186749
```
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'request [/my_index/_search] contains unrecognized parameters: [__elastic_apm_api_method_name], [__elastic_apm_body_ref]')
```
The workaround described in this discussion (putting `SKIP_INSTRUMENT_ELASTICSEARCH=true` in my environment variables) does work, but I would still like to instrument my ElasticSearch calls.

**Context**
I have the latest version of everything:
* a docker container with Elastic 7.4.2
* my Python code runs APM 5.3.2. 

To be noted that I use the Async Python Client for Elastic, whose latest version is only 6.2.0, maybe this could lead to some inconsistencies.

**Comment by beniwohli** [comment] 2019-12-10 09:18
Hi @Thematrixme 

It does indeed look like this is caused by the use of the async client, or more precisely, our lack of support for it.

The good news is that we recently merged initial support for asyncio, so it should be possible to add instrumentation for the async client in a more or less straight forward way. I'll give it a try and report back my findings :)

**Comment by beniwohli** [comment] 2019-12-10 10:32
@Thematrixme quick follow up, what Python version do you run? For our asyncio support, we currently only support 3.7+

**Comment by Thematrixme** [comment] 2019-12-10 12:29
@beniwohli thanks for both your answers. I use Python 3.7 for this project, so I'm good. I'm looking forward to your solution!

**Comment by beniwohli** [comment] 2019-12-10 13:01
@Thematrixme I opened a WIP pull request here: #665

If you want to give it a try in your development/staging environment, you can install it like this:

    pip install "https://github.com/beniwohli/apm-agent-python/archive/elasticsearch-async.zip#egg=elastic-apm==100"

(the `==100` is a little hack to ensure it will install it even though the version in the git branch is the same as the one you already have installed)

**Closed** 2020-02-03 14:38 UTC
