### ISSUE TITLE
Random Read timed out.

### ISSUE THREAD

**Issue by zikphil** [elastic/apm-agent-python#1393] opened 2021-11-10 19:33 UTC
It seems that under heavy load my API service is throwing the following errors at random intervals:

```
Traceback (most recent call last):
  File "/Users/phil/.pyenv/versions/nvp/lib/python3.9/site-packages/elasticapm/transport/http.py", line 86, in send
    response = self.http.urlopen(
  File "/Users/phil/.pyenv/versions/nvp/lib/python3.9/site-packages/urllib3/poolmanager.py", line 417, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/Users/phil/.pyenv/versions/nvp/lib/python3.9/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/phil/.pyenv/versions/nvp/lib/python3.9/site-packages/elasticapm/instrumentation/packages/base.py", line 205, in call_if_sampling
    return wrapped(*args, **kwargs)
  File "/Users/phil/.pyenv/versions/nvp/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/phil/.pyenv/versions/nvp/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/phil/.pyenv/versions/nvp/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/phil/.pyenv/versions/nvp/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/phil/.pyenv/versions/nvp/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/phil/.pyenv/versions/nvp/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='xxxx', port=443): Read timed out. (read timeout=5)
```

Its weird because some traces do successfully come before and after I get those errors without anything changing server side.

Have you seen this before? I am running APM Server on EKS through ECK.

**Comment by basepi** [comment] 2021-11-11 16:19
This looks like the APM Agent timing out on sending something to the APM Server. "Under heavy load" makes me think this may be working as intended. We don't want to block too long on these requests as we'll just get further behind. 

@beniwohli any thoughts?

**Comment by zikphil** [comment] 2021-11-11 17:26
@basepi Is there any retry policies? We would really prefer not losing any traces :)

**Comment by beniwohli** [comment] 2021-11-15 16:43
We currently don't do retries. The agent tries very hard to not significantly increase the memory usage of the host application, and keeping around failed requests would be detrimental to that goal. And as @basepi said, we'd run the risk of falling further and further behind.

In general, the architecture of Elastic APM doesn't give any delivery guarantees. This isn't super well documented at this time, though. It is mentioned in passing [here](https://www.elastic.co/guide/en/apm/server/7.15/common-problems.html#server-es-down):

> Some agents have internal queues or buffers that will temporarily store data if the APM Server goes down. As a general rule of thumb, queues fill up quickly. Assume data will be lost if APM Server goes down.

Some further details are available in the [agent spec](https://github.com/elastic/apm/blob/master/specs/agents/transport.md#transport-errors).

**Comment by zikphil** [comment] 2021-11-15 19:32
> In general, the architecture of Elastic APM doesn't give any delivery guarantees. 
That's worrying. Sounds like an option to allow a retry on the call to the ElasticAPM Server would be nice.

**Comment by basepi** [comment] 2021-11-17 17:24
Retry sounds nice until we're impacting your host adversely due to retries.

The assumption is that users who are running at high load are also probably handling a lot of traffic, and thus tuning their sample rate to something closer to 10% or 1%. At that point, we're only sampling a subset anyway, which means that losing traces is more acceptable than using more resources, since you're not seeing all the traces anyway.

Granted, we still collect durations for unsampled transactions, which means that dropped events will result in slight inaccuracies for overall metrics. But we still think this is a valid tradeoff to avoid impacting a system.

**Comment by beniwohli** [comment] 2022-01-11 13:08
I'll close this as, as far we can tell, the agent works as intended.

**Closed by beniwohli** 2022-01-11 13:08 UTC
Labels: agent-python, community, triage
